export const WORDS = [
  "AGENT",
  "WORLD",
  "ABOUT",
  "HEART",
  "WATER",
  "SIXTY",
  "BOARD",
  "MONTH",
  "MUSIC",
  "PARTY",
  "PIANO",
  "MOUTH",
  "WOMAN",
  "SUGAR",
  "AMBER",
  "DREAM",
  "LAUGH",
  "TIGER",
  "EARTH",
  "MONEY",
  "WORDS",
  "SMILE",
  "LEMON",
  "SOUTH",
  "AFTER",
  "STONE",
  "THING",
  "LIGHT",
  "STORY",
  "POWER",
  "TODAY",
  "RANGE",
  "PEARL",
  "VENOM",
  "PROXY",
  "ROUND",
  "HOVER",
  "CANDY",
  "ABOVE",
  "PHONE",
  "OTHER",
  "SMART",
  "BLACK",
  "MAGIC",
  "FRUIT",
  "RADIO",
  "ROYAL",
  "HONEY",
  "FLAKE",
  "SOUND",
];

export const LETTERS = [
  { key: "Q", id: crypto.randomUUID(), status: "" },
  { key: "W", id: crypto.randomUUID(), status: "" },
  { key: "E", id: crypto.randomUUID(), status: "" },
  { key: "R", id: crypto.randomUUID(), status: "" },
  { key: "T", id: crypto.randomUUID(), status: "" },
  { key: "Y", id: crypto.randomUUID(), status: "" },
  { key: "U", id: crypto.randomUUID(), status: "" },
  { key: "I", id: crypto.randomUUID(), status: "" },
  { key: "O", id: crypto.randomUUID(), status: "" },
  { key: "P", id: crypto.randomUUID(), status: "" },
  { key: "A", id: crypto.randomUUID(), status: "" },
  { key: "S", id: crypto.randomUUID(), status: "" },
  { key: "D", id: crypto.randomUUID(), status: "" },
  { key: "F", id: crypto.randomUUID(), status: "" },
  { key: "G", id: crypto.randomUUID(), status: "" },
  { key: "H", id: crypto.randomUUID(), status: "" },
  { key: "J", id: crypto.randomUUID(), status: "" },
  { key: "K", id: crypto.randomUUID(), status: "" },
  { key: "L", id: crypto.randomUUID(), status: "" },
  { key: "Z", id: crypto.randomUUID(), status: "" },
  { key: "X", id: crypto.randomUUID(), status: "" },
  { key: "C", id: crypto.randomUUID(), status: "" },
  { key: "V", id: crypto.randomUUID(), status: "" },
  { key: "B", id: crypto.randomUUID(), status: "" },
  { key: "N", id: crypto.randomUUID(), status: "" },
  { key: "M", id: crypto.randomUUID(), status: "" },
];
